[list]
[list.default]
driver_name = "mysql"
data_source_name = "root:atk_2018@tcp(127.0.0.1:3306)/dev_test?charset=utf8mb4&parseTime=true&loc=Asia%2FChongqing"
max_open_conn = 20
max_idle_conn = 10
max_conn_life_time = 100